version: '3.7'

services:
  api:
    build:
      context: ./src/wishlist
      target: base
    command: python manage.py run -h 0.0.0.0
    volumes:
      - ./src/wishlist:/usr/src/
    ports:
      - 5000:5000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  api-test:
    build:
      context: ./src/wishlist
      target: test
    command: python -m pytest
    volumes:
      - ./src/wishlist:/usr/src/
    env_file:
      - ./.env.dev
    environment:
      - IS_TEST=true
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    volumes:
      - db_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=password1
      - POSTGRES_DB=app_dev

volumes:
  db_data:
